print("bienvenidos a python")
print("######cartel 6B######)
print("######PROGRAMANDO######")
print("######ESTUDIANDO######")
print("######APRENDIENDO######")
print("#SE CREARAN PROYECTOS#")
print("🤬💀👺🫦🩸💊🖤☢️")
print(#         💡           #)
print(" ##LA FRASE DEL DIA ES##")
print("EL CONOSIMIENTO ES PODER👎👎")
print("ENTONCES APLIQUEMOSLO🚫👎")
print("BIENVENIDOS CLICLO ESCOLAR 2025-2026🤬")